-- 设置自增ID从1000开始
ALTER TABLE "user" ALTER COLUMN id RESTART WITH 1000;
ALTER TABLE user_credential ALTER COLUMN id RESTART WITH 1000;
ALTER TABLE organization ALTER COLUMN id RESTART WITH 1000;
ALTER TABLE role ALTER COLUMN id RESTART WITH 1000;
ALTER TABLE resource ALTER COLUMN id RESTART WITH 1000;
ALTER TABLE session ALTER COLUMN id RESTART WITH 1000;
ALTER TABLE stored_event ALTER COLUMN id RESTART WITH 1000;
